name: epimetheus-log4cats
baseurl: /epimetheus-log4cats
description: Epimetheus Log4cats Metrics
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-RC1+18-bef1a2ac-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
